using DFCStats.Business.Interfaces;
using DFCStats.Domain.DTOs.PasswordResets;
using DFCStats.Data;
using System.Security.Cryptography;
using DFCStats.Data.Entities;
using DFCStats.Domain.Exceptions;
using Microsoft.EntityFrameworkCore;

namespace DFCStats.Business
{
    public class PasswordResetService : IPasswordResetService
    {
        private readonly DFCStatsDBContext _dfcStatsDbContext;
        private readonly IEmailService _emailService;
        private readonly IMessageService _messageService;
        private readonly IUserService _userService;

        // The time in minutes before a password reset request expires
        public int RequestExpiryTimeInMinutes { get; } = 5;

        public PasswordResetService(DFCStatsDBContext dfcStatsDbContext, IEmailService emailService, IMessageService messageService, IUserService userService)
        {
            _dfcStatsDbContext = dfcStatsDbContext;
            _emailService = emailService;
            _messageService = messageService;
            _userService = userService;
        }

        /// <summary>
        /// Issues a password reset email to the user
        /// </summary>
        /// <param name="passwordResetRequestDTO"></param>
        /// <returns></returns>
        public async Task<bool> RequestPasswordResetAsync(PasswordResetRequestDTO passwordResetRequestDTO)
        {
            // Get the user by the email address provided in the request
            var user = await _userService.GetUserByEmailAddressAsync(passwordResetRequestDTO.EmailAddress);

            if (user == null)
                // The user doesn't exist but we don't want to reveal that information specifically
                // so we return false to indicate that the request was not successful
                return false;

            // Check if the user is within the password reset rate limit.
            // If the user has exceeded the maximum number of password reset requests within a 30-minute window, 
            // we return false to indicate that the request was not successful.
            if (await IsWithinPasswordResetRateLimitAsync(user.Id) == false)
                return false;

            // Invalidate any active password reset requests for the user to ensure that only one request is valid at a time
            await InvalidateActivePasswordResetRequestsForUserAsync(user.Id);

            // Generate a reset token for the user
            // Since this is generated by the system it doesn't need to be salted
            var resetToken = GenerateResetToken();

            // Hash the token to store in the database
            var hashedToken = HashToken(resetToken);

            // Create a new PasswordReset entity
            var passwordReset = new PasswordReset
            {
                UserId = user.Id,
                Token = hashedToken,
                CreatedAt = DateTime.UtcNow,
                ExpiresAt = DateTime.UtcNow.AddMinutes(RequestExpiryTimeInMinutes),
                RequesterIpAddress = passwordResetRequestDTO.IpAddress,
            };

            // Save the PasswordReset entity to the database
            _dfcStatsDbContext.PasswordResets.Add(passwordReset);
            await _dfcStatsDbContext.SaveChangesAsync();

            try
            {
                // Create the email message that will be sent to the user
                var message = await _messageService.BuildEmailAsync(
                    template: "Password Reset",
                    subject: "DarloStats - Password Reset",
                    placeHolders: new { Token = resetToken, ExpiryInMinutes = RequestExpiryTimeInMinutes },
                    recipients: new List<string> { user.EmailAddress }
                );
            
                // Send the email
                await _emailService.SendEmailAsync(message);
            } catch (DFCStatsException ex)
            {
                // throw the exception to be handled by the calling code
                throw new DFCStatsException($"Failed to send password reset email: {ex.Message}");
            }

            // Return true to say the email was sent
            return true;
        }

        /// <summary>
        /// Generates a cryptographically secure random token to email to the user
        /// </summary>
        /// <returns></returns>
        private string GenerateResetToken()
        {
            // Generate a random token using a cryptographically secure random number generator
            byte[] bytes = RandomNumberGenerator.GetBytes(32); // 256 bits of entropy
            
            // Return a URL-safe base64 encoded string
            return Convert.ToBase64String(bytes)
                .Replace('+', '-')
                .Replace('/', '_')
                .TrimEnd('='); // URL-safe base64
        }

        /// <summary>
        /// Hashes the token using SHA256 to store in the database
        /// </summary>
        /// <param name="token"></param>
        /// <returns></returns>
        private string HashToken(string token)
        {
            byte[] inputBytes = System.Text.Encoding.UTF8.GetBytes(token);
            byte[] hashBytes = SHA256.HashData(inputBytes);
            return Convert.ToHexString(hashBytes).ToLowerInvariant();
        }
    
        /// <summary>
        /// Invalidates any active password reset requests for the user by setting their UsedAt timestamp to the current time. 
        /// This prevents multiple active requests from being valid at the same time.
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        private async Task InvalidateActivePasswordResetRequestsForUserAsync(Guid userId)
        {
            // Get all active password reset requests for the user that have not been used and have not expired
            var activeRequests = await _dfcStatsDbContext.PasswordResets
                .Where(pr => pr.UserId == userId
                            && pr.UsedAt == null
                            && pr.InvalidatedAt == null
                            && pr.ExpiresAt >= DateTime.UtcNow).ToListAsync();

            // Loop over each of the requests and set their UsedAt timestamp to the current time to invalidate them
            foreach (var request in activeRequests)
            {
                request.InvalidatedAt = DateTime.UtcNow;
            }

            // Update the active password reset requests in the database to reflect that they have been invalidated
            _dfcStatsDbContext.PasswordResets.UpdateRange(activeRequests);

            // Save the changes to the database
            await _dfcStatsDbContext.SaveChangesAsync();
        }

        /// <summary>
        /// Checks if the user has exceeded the maximum number of password reset requests within a 30-minute window.
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="maxRequests"></param>
        /// <returns></returns>
        private async Task<bool> IsWithinPasswordResetRateLimitAsync(Guid userId, int maxRequests = 5)
        {
            // Set the window start time to 30 minutes ago
            var windowStart = DateTime.UtcNow.AddMinutes(-30);

            // Count the number of password reset requests for the user that were created within the last 30 minutes
            var recentRequestCount = await _dfcStatsDbContext.PasswordResets
                .Where(pr => pr.UserId == userId && pr.CreatedAt >= windowStart)
                .CountAsync();

            // Return true if the user is within the rate limit, false otherwise
            return recentRequestCount < maxRequests;
        }

        /// <summary>
        /// Deletes password reset requests that have expired more than 
        /// 30 days ago to keep the database clean and prevent unnecessary data accumulation
        /// </summary>
        /// <returns></returns>
        public async Task DeleteStalePasswordResetRequestsAsync()
        {
            // Set the cutoff date to 30 days ago
            var cutoff = DateTime.UtcNow.AddDays(-30);

            // Get all password reset requests that have expired more than 30 days ago
            var staleRequests = await _dfcStatsDbContext.PasswordResets
                .Where(pr => pr.ExpiresAt < cutoff)
                .ToListAsync();

            // Delete the stale password reset requests from the database
            _dfcStatsDbContext.PasswordResets.RemoveRange(staleRequests);
            await _dfcStatsDbContext.SaveChangesAsync();
        }


    }
}